version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/tutorial
    ports:
      - "8080:8080"
    command: bash -c " pip install -r requirements.txt &&  python manage.py runserver 0.0.0.0:8080"