# Generated by Django 4.0 on 2022-01-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Tutorial_table',
        ),
    ]
