# Generated by Django 4.0 on 2022-01-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_1', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product info'},
        ),
    ]
